export const TEST_IDS = {
  WEATHER_SKELETON_VIEW: 'WEATHER_SKELETON_VIEW',
  FORECAST_DISPLAY: 'FORECAST_DISPLAY',
  WEATHER_GENERAL_VIEW: 'WEATHER_GENERAL_VIEW',
  BOTTOM_TOOLBAR: 'BOTTOM_TOOLBAR',
};
